[theme]
base                  = "light"
primaryColor          = "#2563eb"
backgroundColor       = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor             = "#0f172a"
font                  = "sans serif"

[server]
headless              = true
enableCORS            = false
enableXsrfProtection  = true

[browser]
gatherUsageStats      = false
